version: '3.8'

services:
  db:
    image: mariadb:focal
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    healthcheck:
      test: ['CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 --password="$$(cat /run/secrets/db-password)" --silent']
      interval: 3s
      retries: 5
      start_period: 30s
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backnet
    environment:
      - MYSQL_DATABASE=example
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 3306
      - 33060

  backend:
    build:
      context: backend
      target: builder
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "wget -O /dev/null http://localhost:8000/ping || exit 1"]
      timeout: 10s
    secrets:
      - db-password
    ports:
      - 8000:8000
    networks:
      - backnet
      - frontnet
    depends_on:
      db:
        condition: service_healthy

  proxy:
    build: proxy
    restart: always
    ports:
      - 80:80
    healthcheck:
      test: ["CMD-SHELL", "wget -O /dev/null http://localhost/ping || exit 1"]
      timeout: 10s
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - frontnet

  keycloak:
    build: keycloak
    restart: always
    ports:
      - 8180:8080
    healthcheck:
      test: exit 0
    environment:
      PROXY_ADDRESS_FORWARDING: "true"
      DB_VENDOR: "mariadb"
      DB_ADDR: "db"
      DB_DATABASE: "keycloak"
      DB_USER: "keycloak"
      DB_PASSWORD_FILE: "/run/secrets/db-password"
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
    secrets:
      - db-password
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backnet
      - frontnet

volumes:
  db-data:

secrets:
  db-password:
    file: db/password.txt

networks:
  backnet:
  frontnet:
